# Generated by go2rpm 1.9.0
%bcond_without check

# https://github.com/Azure/kubelogin
%global goipath         github.com/Azure/kubelogin
Version:                0.1.0

%gometa -f


%global common_description %{expand:
A Kubernetes credential (exec) plugin implementing azure authentication.}

%global golicenses      LICENSE
%global godocs          docs CHANGELOG.md CODE_OF_CONDUCT.md SECURITY.md\\\
                        README.md

Name:           %{goname}
Release:        %autorelease
Summary:        A Kubernetes credential (exec) plugin implementing azure authentication

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1

%generate_buildrequires
%go_generate_buildrequires

%build
%gobuild -o %{gobuilddir}/bin/kubelogin %{goipath}

%install
%gopkginstall
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%if %{with check}
%check
%gocheck
%endif

%files
%license LICENSE
%doc docs CHANGELOG.md CODE_OF_CONDUCT.md SECURITY.md README.md
%{_bindir}/*

%gopkgfiles

%changelog
%autochangelog
