# Generated by go2rpm 1.9.0
%bcond_without check
%global debug_package %{nil}

# https://github.com/dnaeon/go-vcr
%global goipath         gopkg.in/dnaeon/go-vcr.v3
%global goaltipaths     gopkg.in/dnaeon/go-vcr.v3/recorder gopkg.in/dnaeon/go-vcr.v3/cassette
%global forgeurl        https://github.com/dnaeon/go-vcr
Version:                3.1.2

%gometa -f


%global common_description %{expand:
Record and replay your HTTP interactions for fast, deterministic and accurate
tests.}

%global golicenses      LICENSE
%global godocs          examples CHANGELOG.org README.md

Name:           %{goname}
Release:        %autorelease
Summary:        Record and replay your HTTP interactions for fast, deterministic and accurate tests

License:        BSD-2-Clause
URL:            %{gourl}
Source:         %{gosource}

%description %{common_description}

%gopkg

%prep
%goprep
%autopatch -p1
rm -rf vendor

%generate_buildrequires
%go_generate_buildrequires

%install
%gopkginstall

%if %{with check}
%check
%gocheck
%endif

%gopkgfiles

%changelog
%autochangelog
